---
- name: Install rustup
  ansible.builtin.shell:
    cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
    executable: /bin/bash

- name: Install stable toolchain
  ansible.builtin.shell:
    cmd: >-
      [ -f {{ ansible_env.HOME }}/.cargo/env ] && source {{ ansible_env.HOME }}/.cargo/env;
      rustup toolchain install stable
  args:
    executable: /bin/bash
  register: toolchain_result
  changed_when: "'installed' in toolchain_result.stdout"

- name: Set stable as default
  ansible.builtin.shell:
    cmd: >-
      [ -f {{ ansible_env.HOME }}/.cargo/env ] && source {{ ansible_env.HOME }}/.cargo/env;
      rustup default stable
  args:
    executable: /bin/bash
  changed_when: false
